/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-17 11:54:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
	request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>회원가입 유효성 검사 정규식</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/script.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<!--script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\">\r\n");
      out.write("</script-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<form id=\"sm\" name=\"pej\" method=\"post\" onsubmit=\"return allCheck()\" action=\"./MemberJoinAction.lg\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-6\">\r\n");
      out.write("				<table class=\"table table-bordered table-dark\">\r\n");
      out.write("\r\n");
      out.write("					<tr bgcolor=\"silver\">\r\n");
      out.write("						<!-- 첫줄 -->\r\n");
      out.write("						<td align=\"center\" colspan=\"2\" style=\"color: black\">회원 기본 정보</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<td>아이디:</td>\r\n");
      out.write("						<td><input type=\"text\" id=\"_id\" name=\"id\" size=12\r\n");
      out.write("							maxlength=12> 4~12자의 영문 대소문자와 숫자로만 입력</td>\r\n");
      out.write("\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 3 -->\r\n");
      out.write("						<td>비밀번호:</td>\r\n");
      out.write("						<td><input type=\"password\" id=\"_pw\" name=\"pw\" size=12\r\n");
      out.write("							maxlength=12> 4~12자의 영문 대소문자와 숫자로만 입력</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 4 행-->\r\n");
      out.write("						<td>비밀번호확인:</td>\r\n");
      out.write("						<td><input type=\"password\" id=\"_pw2\" size=12 maxlength=12></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 5 -->\r\n");
      out.write("						<td>메일주소:</td>\r\n");
      out.write("						<td><input type=\"text\" id=\"_mail\" name=\"email\" size=15>\r\n");
      out.write("							예) id@gmail.com</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 6 -->\r\n");
      out.write("						<td>이름:</td>\r\n");
      out.write("						<td><input type=\"text\" id=\"_name\" name=\"name\" size=15\r\n");
      out.write("							maxlength=4></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr bgcolor=\"silver\">\r\n");
      out.write("						<!-- 첫줄 -->\r\n");
      out.write("						<td align=\"center\" colspan=\"2\" style=\"color: black\">개인 신상 정보</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>주소</td>\r\n");
      out.write("						\r\n");
      out.write("						<td><input type=\"text\" id=\"tbox1\" name=\"addr\"\r\n");
      out.write("							placeholder=\"우편번호\" size=8> <input type=\"button\"\r\n");
      out.write("							onclick=\"addrFind()\" value=\"우편번호 찾기\"><br> <input\r\n");
      out.write("							type=\"text\" id=\"tbox2\" name=\"addr\" placeholder=\"주소\" size=28><br>\r\n");
      out.write("							<input type=\"text\" id=\"tbox4\" name=\"addr\" placeholder=\"참고항목\"\r\n");
      out.write("							size=28> <input type=\"text\" id=\"tbox3\" name=\"addr\"\r\n");
      out.write("							placeholder=\"상세주소\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 7 -->\r\n");
      out.write("						<td>주민등록번호:</td>\r\n");
      out.write("						<td><input type=\"text\" id=\"_ju\" name=\"pin\" size=15\r\n");
      out.write("							minlength=13 maxlength=13> 예) 1234561234567</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 8 -->\r\n");
      out.write("						<td>생일:</td>\r\n");
      out.write("						<td><input type=\"text\" id=\"birth\" name=\"year\" size=5maxlength=12>년 \r\n");
      out.write("						\r\n");
      out.write("							<select id=\"month\" name=\"month\">\r\n");
      out.write("								<option value=\"1\">1</option>\r\n");
      out.write("								<option value=\"2\">2</option>\r\n");
      out.write("								<option value=\"3\">3</option>\r\n");
      out.write("								<option value=\"4\">4</option>\r\n");
      out.write("								<option value=\"5\">5</option>\r\n");
      out.write("								<option value=\"6\">6</option>\r\n");
      out.write("								<option value=\"7\">7</option>\r\n");
      out.write("								<option value=\"8\">8</option>\r\n");
      out.write("								<option value=\"9\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("							</select>월 \r\n");
      out.write("						\r\n");
      out.write("						<select id=\"day\" name=\"day\">\r\n");
      out.write("								<option value=\"1\">1</option>\r\n");
      out.write("								<option value=\"2\">2</option>\r\n");
      out.write("								<option value=\"3\">3</option>\r\n");
      out.write("								<option value=\"4\">4</option>\r\n");
      out.write("								<option value=\"5\">5</option>\r\n");
      out.write("								<option value=\"6\">6</option>\r\n");
      out.write("								<option value=\"7\">7</option>\r\n");
      out.write("								<option value=\"8\">8</option>\r\n");
      out.write("								<option value=\"9\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("								<option value=\"13\">13</option>\r\n");
      out.write("								<option value=\"14\">14</option>\r\n");
      out.write("								<option value=\"15\">15</option>\r\n");
      out.write("								<option value=\"16\">16</option>\r\n");
      out.write("								<option value=\"17\">17</option>\r\n");
      out.write("								<option value=\"18\">18</option>\r\n");
      out.write("								<option value=\"19\">19</option>\r\n");
      out.write("								<option value=\"20\">20</option>\r\n");
      out.write("								<option value=\"21\">21</option>\r\n");
      out.write("								<option value=\"22\">22</option>\r\n");
      out.write("								<option value=\"23\">23</option>\r\n");
      out.write("								<option value=\"24\">24</option>\r\n");
      out.write("								<option value=\"25\">25</option>\r\n");
      out.write("								<option value=\"26\">26</option>\r\n");
      out.write("								<option value=\"27\">27</option>\r\n");
      out.write("								<option value=\"28\">28</option>\r\n");
      out.write("								<option value=\"29\">29</option>\r\n");
      out.write("								<option value=\"30\">30</option>\r\n");
      out.write("								<option value=\"31\">31</option>\r\n");
      out.write("						</select>일</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 9 -->\r\n");
      out.write("						<td>관심분야:</td>\r\n");
      out.write("						<td><input type=\"checkbox\" value=\"컴퓨터\" name=\"hobby\">컴퓨터\r\n");
      out.write("							<input type=\"checkbox\" value=\"인터넷\" name=\"hobby\">인터넷 <input\r\n");
      out.write("							type=\"checkbox\" value=\"여행\" name=\"hobby\">여행 <input\r\n");
      out.write("							type=\"checkbox\" value=\"영화감상\" name=\"hobby\">영화감상 <input\r\n");
      out.write("							type=\"checkbox\" value=\"음악감상\" name=\"hobby\">음악감상\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<!-- 9 -->\r\n");
      out.write("						<td>자기소개:</td>\r\n");
      out.write("						<td><textarea id=\"my_intro\" name=\"intro\" cols=\"55\" rows=\"5\"\r\n");
      out.write("								maxlength=\"700\"></textarea></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("							value=\"회원 가입\"> <input type=\"reset\" value=\"다시입력\">\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
